# permissions for end users to edit ovms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovms-editor-role
rules:
- apiGroups:
  - intel.com
  resources:
  - modelserver
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intel.com
  resources:
  - modelserver/status
  verbs:
  - get
